### 1. GET all roles : id+name
GET http://localhost:3001/api/offices
Content-Type: application/json

###

###

# Login
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "aaaaaaaa@aaaaaaaaaaaa.com",
  "password": "password"
}

###

# Login admin
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "admin@participium.local",
  "password": "participium"
}

### 
## Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current

###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current

###

# Registration
POST http://localhost:3001/api/registration
content-type: application/json

{
  "username": "alessioVialdi",
  "first_name": "alessio",
  "last_name": "vivaldi",
  "email": "aaaaaaaa@aaaaaaaaaaa.com",
  "email_notifications": true,
  "password": "password"
}

###

# Registration user
POST http://localhost:3001/api/operators
content-type: application/json

{
  "username": "alessioVivaldi",
  "first_name": "alessio",
  "last_name" : "vivaldi",
  "email" : "aaaaaaaa@aaaaaaaaaaaa.com",
  "password": "password"
}

###