### 1. GET all operators with office=2
GET http://localhost:3001/api/assign_list?office_id=2

###

###

# Login
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "alessioVivaldii",
  "password": "password"
}

###

# Login admin
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "admin@participium.local",
  "password": "participium"
}

### 
## Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current

###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current

###

# Registration
POST http://localhost:3001/api/registration
content-type: application/json

{
  "username": "alessioVialdi",
  "first_name": "alessio",
  "last_name": "vivaldi",
  "email": "aaaaaaaa@aaaaaaaaaaa.com",
  "email_notifications": true,
  "password": "password"
}

###

# Registration user
POST http://localhost:3001/api/admin/createuser
content-type: application/json

{
  "username": "alessioVivaldii",
  "email" : "aaaaaaaa@aaaaaaaaa.com",
  "password": "password",
  "office_id": 2,
  "role": 2
}

###



###

# Login
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "melo@participium.local",
  "password": "password"
}

###

# Try to send verification email
POST http://localhost:3001/api/citizens/verification-code
content-type: application/json

{
  "userId": "1"
}

###

# Verify email
POST http://localhost:3001/api/citizens/verify-email
content-type: application/json

{
  "userId": "1",
  "code": "268759"
}

###